# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
# Extension metadata
version = "0.1.0"
title = "OmniGraph Optics"
description = "Optical system builder with custom OmniGraph nodes."
authors = ["Your Name <your@email.com>"]

[core]
enabled = true


[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.commands" = {}
"omni.graph.window.action" = {}
"omni.graph.core" = {}
"omni.kit.window.extensions" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.console" = {}
"omni.kit.selection" = {}

[ogn]
paths = ["mit/onmigraph_optics/ogn"]


[settings]


[[python.module]]  # Main python module this extension provides, it will be publicly available as "import mit.onmigraph_optics"
name = "mit.onmigraph_optics"


[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]


[[test]]
dependencies = [
]

args = [
]